/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.flow_task;

import javax.swing.ImageIcon;
import com.mycompany.flow_task.task.frmTaskOpen;
import com.mycompany.flow_task.task.frmTaskList;

import com.mycompany.flow_task.costumer.frmCostumerList;
import com.mycompany.flow_task.costumer.frmCostumerEdit;

import com.mycompany.flow_task.employee.frmEmployeeList;
import com.mycompany.flow_task.employee.frmEmployeeEdit;
import com.mycompany.flow_task.employee.employee;
import com.mycompany.flow_task.employee.sqlEmployee;

import com.mycompany.flow_task.process_type.frmProcessTypeList;
import com.mycompany.flow_task.process_type.frmProcessTypeEdit;

import com.mycompany.flow_task.department.frmDepartmentEdit;
import com.mycompany.flow_task.department.sqlDepartment;
import com.mycompany.flow_task.notepad.frmNotepad;

import com.mycompany.flow_task.title.frmTitleEdit;

import com.mycompany.flow_task.settings.frmSettingUser;
import com.mycompany.flow_task.settings.frmSettingsAccount;
import com.mycompany.flow_task.settings.frmSettingShift;
import javax.swing.JOptionPane;

/**
 *
 * @author semih
 */
public class frmHome extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmHome.class.getName());

    /**
     * Creates new form frmHome
     */
    public frmHome() {
        initComponents();
        
        this.setIconImage(new ImageIcon(getClass().getResource("/resources/logo_icon.png")).getImage());
        lblIcon.setIcon(new ImageIcon(getClass().getResource("/resources/logo.png")));
        
        jMenuBar1.setVisible(false);
        this.setTitle("[HATALI GİRİŞ]");
        JOptionPane.showMessageDialog(null, "HATALI GİRİŞ YAPTINIZ!\nPROGRAMI KAPATIP TEKRAR GİRİN", "HATALI GİRİŞ", JOptionPane.ERROR_MESSAGE);
    }
    
    public frmHome(employee _employee) {
        initComponents();
        
        this.setIconImage(new ImageIcon(getClass().getResource("/resources/logo_icon.png")).getImage());
        lblIcon.setIcon(new ImageIcon(getClass().getResource("/resources/logo.png")));
        
        this._employee = _employee;
        refresh();
    }

    employee _employee;
    sqlEmployee sEmployee = new sqlEmployee();
    sqlDepartment sDepartment = new sqlDepartment();
    
    private void refresh(){
        _employee = sEmployee.getEmployeeInfo(_employee.getId());
        
        this.setTitle(this._employee.getId() + " - " + this._employee.getName() + " [" + sDepartment.getDepartmentName(this._employee.getDepartmentID()) + "]");
        mnAdmin.setVisible(this._employee.isAdmin());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnTskOpen = new javax.swing.JMenuItem();
        mnTskList = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mnAdmin = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(250, 238, 224));

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1102, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("İşler");

        mnTskOpen.setText("İş Aç");
        mnTskOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTskOpenActionPerformed(evt);
            }
        });
        jMenu1.add(mnTskOpen);

        mnTskList.setText("İş Takip");
        mnTskList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTskListActionPerformed(evt);
            }
        });
        jMenu1.add(mnTskList);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Müşteriler");

        jMenuItem8.setText("Listele");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("İşlemler");

        jMenuItem9.setText("Listele");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("Çalışan Bilgileri");

        jMenuItem10.setText("Listele");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem10);

        jMenuBar1.add(jMenu6);

        jMenu5.setText("Not Defteri");

        jMenuItem13.setText("Aç");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem13);

        jMenuBar1.add(jMenu5);

        jMenu4.setText("Ayarlar");

        jMenuItem1.setText("Kullanıcı Ayarı");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem2.setText("Hesap Ayarı");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem4.setText("Mesai Bilgisi");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem3.setText("Çıkış Yap");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        mnAdmin.setText("Yönetici Ayarları");

        jMenuItem5.setText("Müşteri Ayarları");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mnAdmin.add(jMenuItem5);

        jMenuItem7.setText("Çalışan Ayarları");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        mnAdmin.add(jMenuItem7);

        jMenuItem6.setText("İşlem Ayarları");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        mnAdmin.add(jMenuItem6);

        jMenuItem11.setText("Ünvan Ayarları");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        mnAdmin.add(jMenuItem11);

        jMenuItem12.setText("Departman");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        mnAdmin.add(jMenuItem12);

        jMenuBar1.add(mnAdmin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnTskOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTskOpenActionPerformed
        // TODO add your handling code here:
        refresh();
        
        frmTaskOpen taskOpen = new frmTaskOpen(_employee);
        jDesktopPane1.add(taskOpen);
        taskOpen.setVisible(true);
    }//GEN-LAST:event_mnTskOpenActionPerformed

    private void mnTskListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTskListActionPerformed
        // TODO add your handling code here:
        refresh();
        
        frmTaskList list = new frmTaskList(_employee);
        jDesktopPane1.add(list);
        list.setVisible(true);
    }//GEN-LAST:event_mnTskListActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        refresh();
        
        frmSettingUser settingUser = new frmSettingUser(_employee);
        jDesktopPane1.add(settingUser);
        settingUser.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        refresh();
        
        frmSettingsAccount settingAccount = new frmSettingsAccount(_employee);
        jDesktopPane1.add(settingAccount);
        settingAccount.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        refresh();
        
        frmSettingShift settingShift = new frmSettingShift(_employee);
        jDesktopPane1.add(settingShift);
        settingShift.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        frmLogin login = new frmLogin();
        
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        refresh();
        
        frmCostumerList customerList = new frmCostumerList();
        jDesktopPane1.add(customerList);
        customerList.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        refresh();
        
        frmProcessTypeList typeList = new frmProcessTypeList();
        jDesktopPane1.add(typeList);
        typeList.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        refresh();
        
        frmEmployeeList employeeList = new frmEmployeeList();
        jDesktopPane1.add(employeeList);
        employeeList.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        refresh();
        
        frmCostumerEdit customerEdit = new frmCostumerEdit(_employee);
        jDesktopPane1.add(customerEdit);
        customerEdit.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        refresh();
        
        frmEmployeeEdit employeeEdit = new frmEmployeeEdit(_employee);
        jDesktopPane1.add(employeeEdit);
        employeeEdit.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        refresh();
        
        frmProcessTypeEdit processTypeEdit = new frmProcessTypeEdit(_employee);
        jDesktopPane1.add(processTypeEdit);
        processTypeEdit.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        refresh();
        
        frmTitleEdit titleEdit = new frmTitleEdit(_employee);
        jDesktopPane1.add(titleEdit);
        titleEdit.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        refresh();
        
        frmDepartmentEdit departmentEdit = new frmDepartmentEdit(_employee);
        jDesktopPane1.add(departmentEdit);
        departmentEdit.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        refresh();
        
        frmNotepad note = new frmNotepad(_employee);
        jDesktopPane1.add(note);
        note.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmHome().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JMenu mnAdmin;
    private javax.swing.JMenuItem mnTskList;
    private javax.swing.JMenuItem mnTskOpen;
    // End of variables declaration//GEN-END:variables
}
